---
- name: Get user
  ansible.builtin.user:
    name: '{{ user_name }}'
    state: present
  register: user

- name: Create symlink to iCloud
  file:
    state: link
    src: '{{ user.home }}/Library/Mobile Documents/com~apple~CloudDocs'
    dest: '{{ user.home }}/iCloud'

- name: Create symlink to builds
  file:
    state: link
    src: '{{ user.home }}/iCloud/builds'
    dest: '{{ user.home }}/builds'
