---
- name: Get user
  ansible.builtin.user:
    name: '{{ user_name }}'
    state: present
  register: user

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: '{{ user.home }}/.config/bash'
    owner: '{{ user.name }}'
    group: '{{ user.group }}'
    state: directory
    mode: u=r,g=r,o=rw

- name: Remove existing bash configuration files
  file:
    state: absent
    dest: '{{ user.home }}/.config/bash/{{ item.path }}'
  with_filetree: ../templates
  when: item.state == 'file'

- name: Copy bash configuration files
  copy:
    src: '{{ item.src }}'
    dest: '{{ user.home }}/.config/bash/{{ item.path }}'
    mode: u=r,g=r,o=rw
  with_filetree: ../templates
  when: item.state == 'file'

- name: Create a symbolic link
  ansible.builtin.file:
    src: '{{ user.home }}/.config/bash/{{ item }}'
    dest: '{{ user.home }}/.{{ item }}'
    owner: '{{ user.name }}'
    group: '{{ user.group }}'
    mode: u=r,g=r,o=rw
    state: link
  with_items:
    - bashrc
    - inputrc


# sudo apt install -y fzf ripgrep bat eza zoxide plocate btop fd-find

# export BASH_CONFIG_PATH="$HOME/.config/bash"

# mkdir -p $BASH_CONFIG_PATH

# cp $CONFIG_PATH/bash/aliases $BASH_CONFIG_PATH/aliases
# cp $CONFIG_PATH/bash/init $BASH_CONFIG_PATH/init
# cp $CONFIG_PATH/bash/prompt $BASH_CONFIG_PATH/prompt
# cp $CONFIG_PATH/bash/shell $BASH_CONFIG_PATH/shell

# # Configure the bash shell using defaults
# [ -f "~/.bashrc" ] && mv ~/.bashrc ~/.bashrc.bak
# cp $CONFIG_PATH/bash/bashrc ~/.bashrc

# # Load the PATH for use later in the installers
# source $BASH_CONFIG_PATH/shell

# [ -f "~/.inputrc" ] && mv ~/.inputrc ~/.inputrc.bak
# # Configure the inputrc using defaults
# cp $CONFIG_PATH/bash/inputrc ~/.inputrc

