---
# https://dev.to/katsuhisa91/my-ansible-playbook-for-setup-m1-mac-2j9m
- hosts: localhost
  connection: local
  gather_facts: true
  become: true

  vars_prompt:
  - name: user_name
    prompt: Which user do you wish to modify?
    private: false

  # - name: github_access_token
  #   prompt: What is your github access token?
  #   private: false

  # tasks:
  # - name: Install apt packages
  #   ansible.builtin.apt:
  #     name:
  #       - python3-psutil
  #     state: present

  roles:
  # - git
  # - terminal
  # - flatpak
  # - signal
  # - code
  # - steam
  # - fonts
  - nautilus

  # tasks:
  # - name: Remove default snaps
  #   community.general.snap:
  #     name: 
  #       - firefox
  #       - thunderbird
  #     state: disabled

  # - name: Remove default snaps
  #   community.general.snap:
  #     name: 
  #       - firefox
  #       - thunderbird
  #     state: absent

  # - name: Remove apt packages
  #   ansible.builtin.apt:
  #     name:
  #       - libreoffice-*
  #       # - libreoffice-calc
  #       # - libreoffice-core
  #       # - libreoffice-math
  #       # - libreoffice-impress
  #       # - libreoffice-pdfimport
  #       # - libreoffice-writer
  #       - rhythmbox
  #       - transmission-gtk
  #     state: absent
  #     purge: true

  # - name: Install apt packages
  #   ansible.builtin.apt:
  #     name:
  #       - steam-devices
  #     state: present
