export BASH_CONFIG_PATH="$HOME/.config/bash"

source $BASH_CONFIG_PATH/shell
source $BASH_CONFIG_PATH/aliases
source $BASH_CONFIG_PATH/prompt
source $BASH_CONFIG_PATH/init

# Editor used by CLI
export EDITOR="nvim"
export SUDO_EDITOR="$EDITOR"
